project:
  type: website
  output-dir: docs
  render: 
    - "*.qmd"
    - "*.ipynb"
    - "!exercises_notebook/"

website:
  title: "Machine learning course for VIVE"
  favicon: images/favicon.ico
  search: false
  navbar:
    background: rgb(144,26,30)
    right:
      - href: index.qmd
        text: Home
format:
  html:
    page-layout: full
    theme:
      light: flatly 
      dark: darkly
    toc: false
    toc-depth: 3